version: '3.8'

services:
  # Serviço da aplicação Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:13
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - laravel-network

  # Serviço do servidor NGINX
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel-network

# Configuração de rede
networks:
  laravel-network:
    driver: bridge

# Configuração de volumes
volumes:
  db_data:
